const products = [
  {
    _id: '1',
    name: 'Marygold',
    image: '/images/p4.jpg',
    description: 'High Quality',
    brand: 'Daisy',
    category: 'Flower',
    price: 89,
    rating: 4.5,
    numReviews: 12,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '2',
    name: 'Rose',
    image: '/images/p2.jpg',
    description: 'High Quality',
    brand: 'Rose',
    category: 'Flower',
    price: 599,
    rating: 4.0,
    numReviews: 8,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '3',
    name: 'Lotus',
    image: '/images/p3.jpg',
    description: 'High Quality',
    brand: 'Lotus',
    category: 'Flower',
    price: 300,
    rating: 3,
    numReviews: 12,
    isNew: false,
    reviews: [],
    stock: 0,
  },
  {
    _id: '4',
    name: 'Daisy',
    image: '/images/p1.jpg',
    description: 'High Quality',
    brand: 'Daisy',
    category: 'Flower',
    price: 399,
    rating: 5,
    numReviews: 12,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '5',
    name: 'Pink Rose',
    image: '/images/p5.jpg',
    description: 'High Quality',
    brand: 'Rose',
    category: 'Flower',
    price: 49,
    rating: 3.5,
    numReviews: 10,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '6',
    name: 'Tulips',
    image: '/images/p6.jpg',
    description: 'High Quality',
    brand: 'Tulips',
    category: 'Flower',
    price: 49,
    rating: 4,
    numReviews: 1,
    isNew: false,
    reviews: [],
    stock: 7,
  },
]

export default products
